### ISSUE TITLE
error module not found

### ISSUE THREAD

**Issue by poplevente** [ecraft/i18n-fetch-translations#11]
Hey guys,

i'm getting the following error: 
loader.js:247 Uncaught Error: Could not find module `fetch` imported from `ember-i18n-fetch-translations/initializers/ember-i18n-fetch-translations`

do you know what could be? where can i start debugging?

**Comment by olleolleolle** [comment]
Wild speculation: it could be that some part of some thing is expecting the global `fetch` module to exist, when it doesn't - perhaps because the code is running in IE10 and `ie 10` isn't in the list of `targets.js`?

**Comment by poplevente** [comment]
i had to add ember-fetch to the dependencies. maybe running an older ember version caused this
