### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by poplevente** [ecraft/i18n-fetch-translations#12]
Now i got a different issue. i've been adding the fetch translations recently and i don't have a localstorage for the past items and now i get an error like

ember-i18n-fetch-translations.js:12 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.initialize (ember-i18n-fetch-translations.js:12)
    at ember.debug.js:5628
    at ember.debug.js:5644
    at Object.visit [as default] (ember.debug.js:53407)
    at DAG.topsort (ember.debug.js:2583)
    at Class._runInitializer (ember.debug.js:5643)
    at Class.runInstanceInitializers (ember.debug.js:5626)
    at Class._bootSync (ember.debug.js:3881)
    at Class.didBecomeReady (ember.debug.js:4898)

at these lines : 
var translations = JSON.parse(localStorage.getItem('ember-i18n-fetch-translations-' + ewConfig.namespace));
    Object.keys(translations).forEach(function (locale) {
      i18n.addTranslations(locale, translations[locale]);
    });

did anyone encounter the same before?

**Comment by olleolleolle** [comment]
Would you expect the addon to raise a described error, instead?

**Comment by poplevente** [comment]
Hey, i have a translation.json (full with translations). i would like to use that data for the i18n

**Comment by poplevente** [comment]
nmv, my mistake. my json was bad and i got back null. an error handling there would be nice though as a feature. but good work, now everything works!

**Comment by mriska** [comment]
@poplevente Thank you for the feedback. It is always fun to hear that someone is using our addon. We will look into adding some better error handling for these kind of situations.
