### ISSUE TITLE
More robust handling around fetching translations and storing in local storage

### ISSUE THREAD

**Issue by nanderss** [ecraft/i18n-fetch-translations#2]
Currently we allow advancing in the initializer even if fetching translations from the server failed. We should allow advancing if we already have translations in local storage, but not if we don't have any. 

Maybe we should in the finally-block in the initializer check if we have something in local storage, and fail if we don't?

This will make us more robust, and still support offline scenarios.

**Comment by mriska** [comment]
I'll see if I can get this fixed tonight.

**Comment by nanderss** [comment]
@mriska I don't think this is super urgent, the addon works well without this.

If you do implement this however, it might be a good idea to in the error message we give if no translations can be loaded and nothing is cached point out that this might be because the namespace is incorrect in the config-file. This happened to @olleolleolle and me.
